/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "primary": "#00687a",
        "primary-container": "var(--primary-container)",
        "brand-primary-hover": "var(--brand-primary-hover)",
        "brand-primary-active": "#006B7D",
        "brand-primary-subtle": "var(--brand-primary-subtle)",
        "primary-fixed": "#acedff",
        "primary-fixed-dim": "#60d5f2",
        "surface": "var(--surface)",
        "surface-canvas": "var(--surface-canvas)",
        "surface-panel": "var(--surface-panel)",
        "surface-sidebar": "var(--surface-sidebar)",
        "surface-container": "var(--surface-panel)",
        "surface-container-high": "var(--surface-sidebar)",
        "surface-container-highest": "var(--surface-panel)",
        "surface-container-low": "var(--surface)",
        "surface-container-lowest": "var(--surface-canvas)",
        "border-strong": "var(--border-strong)",
        "border-subtle": "var(--border-subtle)",
        "status-secure": "#059669",
        "status-warning": "#D97706",
        "status-danger": "#DC2626",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-primary-container": "#002f38",
        "tertiary": "#904d00",
        "tertiary-container": "#ce7e33",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.375rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "gutter": "0.75rem",
        "margin": "1rem",
      },
      fontFamily: {
        sans: ["'Public Sans'", "system-ui", "-apple-system", "sans-serif"],
        "body-sm": ["'Public Sans'", "sans-serif"],
        "body-md": ["'Public Sans'", "sans-serif"],
        "label-sm": ["'Public Sans'", "sans-serif"],
        "label-md": ["'Public Sans'", "sans-serif"],
        "headline-md": ["'Public Sans'", "sans-serif"],
        "headline-lg": ["'Public Sans'", "sans-serif"],
        "headline-xl": ["'Public Sans'", "sans-serif"],
        "code-sm": ["'Public Sans'", "monospace"],
      },
      fontSize: {
        "label-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.125rem", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "label-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
        "headline-md": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-sm": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
